name: "action-trigger"
on:
  push:
    branches:
      - dev
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  repository_dispatch:
    types: [dispatch-event]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Action redebug-deployment
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/joveryz/redebug-deployment/dispatches \
            -d '{"event_type":"dispatch-event"}'

      - name: Trigger Action venusie-deployment
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/joveryz/venusie-deployment/dispatches \
            -d '{"event_type":"dispatch-event"}'
